### ISSUE TITLE
Atualização do projeto no Github

### ISSUE THREAD

**Issue by jlsilva01** [Guna-ME/FisioRangers#1]
Pessoal, não aparece ninguém ainda como contributors do projeto e projeto há 1 semana sem atualizações.

Somente a Maria Eduarda publicou alguma coisa?
Todos tem acesso já e estão fazendo as atividades em paralelo?
Sugiro já atualizar o readme e demais atividades dos outros membros do time.

Qq dúvida, me avisem na aula.

**Comment by Guna-ME** [comment]
Boa Noite, Professor, 

Iniciamos o trabalho commitando o Read me, e realizando em conjunto o Modelo Físico. Estamos fazendo o planejamento de tarefas para distribuir de acordo o que cada um irá fazer.
