### ISSUE TITLE
Scripts DDL - Criação BD

### ISSUE THREAD

**Issue by Guna-ME** [Guna-ME/FisioRangers#3]
Criação dos Scripts de DDL;

**Comment by Guna-ME** [comment]
@JeffAlexandrino poderia add os indices no código?? De acordo com o dicionário.

**Comment by JeffAlexandrino** [comment]
> @JeffAlexandrino poderia add os indices no código?? De acordo com o dicionário.

Ok, posso sim

**Comment by JeffAlexandrino** [comment]
Feito, só não tenho absoluta certeza que está perfeitamente correto, então se possivel gostaria que alguem desse uma conferida

**Comment by Guna-ME** [comment]
@JVGFern e @KinhoMilak podem dar uma olhadinha?
