### ISSUE TITLE
Dicionário de Dados

### ISSUE THREAD

**Issue by Guna-ME** [Guna-ME/FisioRangers#7]
Preenchimento do Dicionário com índices;

**Comment by Guna-ME** [comment]
@Guna-ME

**Comment by Guna-ME** [comment]
Atualizado, adicionado a maioria das tabelas e informações, necessita complementar;

**Comment by Guna-ME** [comment]
Falta apenas inserir os indices,
 @JVGFern ou @JeffAlexandrino podem ver isso?

**Comment by JeffAlexandrino** [comment]
> Falta apenas inserir os indices, @JVGFern ou @JeffAlexandrino podem ver isso?

Possi fazer sim, mas é um arquivo específico ou os 3?

**Comment by Guna-ME** [comment]
Apenas o último (2)

**Comment by Guna-ME** [comment]
@JVGFern e @KinhoMilak podem olhar os index aqui também??
