### ISSUE TITLE
Slide de Apresentação

### ISSUE THREAD

**Issue by Guna-ME** [Guna-ME/FisioRangers#8]
Personalizar um slide para apresentação do projeto;

**Comment by JeffAlexandrino** [comment]
https://www.canva.com/design/DAF1flMmOU8/5NrjvjbiwlnJILddLIQ_XA/edit?utm_content=DAF1flMmOU8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Comecei a montagem dos slides, qualquer um com link pode acessar e editar os slides
